# Generated by Django 6.0 on 2026-01-11 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Імʼя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
