# Generated by Django 6.0 on 2025-12-20 19:37

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва бренду')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='year_manufacture',
            field=models.PositiveIntegerField(default=main.models.current_year, validators=[main.models.validate_year], verbose_name='Рік виробництва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.brand', verbose_name='Бренд'),
        ),
    ]
