# Generated by Django 6.0 on 2025-12-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_product_year_manufacture_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(default='Не вказано', max_length=100, verbose_name='Країна походження'),
        ),
    ]
