# Generated by Django 6.0 on 2025-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ші_sells_better',
            field=models.BooleanField(default=False, verbose_name='Найчастіще купують'),
        ),
    ]
