# Generated by Django 6.0 on 2025-12-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_ші_sells_better'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ші_sells_better',
            new_name='is_sells_better',
        ),
    ]
