# Generated by Django 6.0 on 2025-12-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('mark', models.ImageField(upload_to='')),
            ],
        ),
    ]
