# Generated by Django 6.0 on 2025-12-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='created_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
