# Generated by Django 6.0 on 2025-12-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitereview',
            old_name='mark',
            new_name='rating',
        ),
    ]
