# Generated by Django 6.0 on 2026-01-04 14:42

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_mark_sitereview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Відгуки про товар', 'verbose_name_plural': 'Відгуки про товари'},
        ),
        migrations.AlterModelOptions(
            name='sitereview',
            options={'ordering': ['-created_time'], 'verbose_name': 'Відгуки про сайт', 'verbose_name_plural': 'Відгуки про сайт'},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[main.validators.rating_validator]),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='rating',
            field=models.IntegerField(validators=[main.validators.rating_validator]),
        ),
    ]
