# Generated by Django 6.0 on 2026-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_main_produc_id_f3d40d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='main_brand_name_d5e10d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
    ]
