# Generated by Django 6.0 on 2026-01-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_brand_main_brand_name_d5e10d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='is_available',
        ),
    ]
