# Generated by Django 6.0 on 2026-01-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_available_product_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'is_available'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
