# Generated by Django 6.0 on 2026-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_product_options_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'is_available'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
